# Generated by Django 3.0.8 on 2020-07-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=16),
        ),
    ]
